# Site
repository: navpreetnp7.github.io #sproogen/resume-theme
#favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Navpreet Singh
title: Graduate Student at New York University (Courant)
email: navpreet.np1@gmail.com

# Dark Mode (true/false/never)
darkmode: never

# Social links
# twitter_username: facespics
github_username:  navpreetnp7
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: navpreet_np
linkedin_username: navpreetsingh7
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  
  I am a masters student at NYU Courant primarily interested in Statistics, Machine Learning and Deep Learning.
  I have an experience of 2 years in Software Engineering including Backend Development (Oracle) and Machine Learning (NLP and ComputerVision).


content:

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Delhi Technological University
        caption: 2014 - 2018
        sub_title: Bachelor of Technology in Computer Science
        quote: >
          Delhi Technological University (DTU), formerly known as the Delhi College of Engineering (DCE) is a state university in New Delhi, India. It was established in 1941 as Delhi Polytechnic.
        description: | # this will include new lines to allow paragraphs
          During my time at DTU I gained alot of interest in Software Engineering. I learnt many key skills such as teamwork, punctuality and stick-to-itiveness that has been useful to me throughout my career. 

          

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Wissen Technology
        link: wissen.com
        # link_text: wissen.com
        sub_title: Software Engineer
        caption: November 2020 - January 2021
        quote: >
          Wissen is a leading technology consulting and solutions company practice primarily geared towards the domains of Banking & Finance, Telecom, and Healthcare.
        description: | # this will include new lines to allow paragraphs
            My work focused on training and implementing a Language Model for the Intelligent Search application for our client Baker Hughes. I implemented pdf parsing on the technical pdf documents as well as the BERT Transformer language model using sentence similarity for intelligent search.
      
      - layout: left
        title: MetricStream
        link: metricstream.com
        # link_text: metricstream.com
        sub_title: Member of Technical Staff - Developer
        caption: September 2018 - July 2020
        quote: >
          MetricStream is the world’s largest independent provider of governance, risk, and compliance (GRC) products & solutions.
        description: | # this will include new lines to allow paragraphs
            My primary focus was on the backend (Oracle SQL) part of the GRC Application for Risks and Audit modules with some work on custom configuration for the GRC application as well using the M7 platform.

      - layout: left
        title: inkers.ai
        link: inkers.ai
        # link_text: inkers.ai
        sub_title: Machine Learning Intern
        caption: March 2019 - September 2019
        quote: >
          We design and develop deep large-scale AI and ML vision solutions for Enterprises, Defence and Security Organizations. 
        description: | # this will include new lines to allow paragraphs
            This was a huge learning experience for me where I learnt to implement deep learning models for Computer Vision as well as Natural Language Processing.


  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Traffic vehicle tracking and speed estimation
        link: github.com/navpreetnp7/Car-Tracking-and-speed-estimation
        # link_text: Project Website
        additional_links:
          - title:  Car-Tracking-and-speed-estimation
            icon: fab fa-github
            url: github.com/navpreetnp7/Car-Tracking-and-speed-estimation
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Track vehicles on the road and estimate their speed.
        description: | # this will include new lines to allow paragraphs
          Implemented using Pretrained YOLOv4 on COCO dataset for object detection and DeepSort Model for object tracking.
          ![Traffic](/images/demo.gif "Traffic")


  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
