# Site
repository: navpreetnp7.github.io #sproogen/resume-theme
#favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Navpreet Singh
title: Graduate Student at New York University (Courant)
email: navpreet.np1@gmail.com

# Dark Mode (true/false/never)
darkmode: never

# Social links
# twitter_username: facespics
github_username:  navpreetnp7
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: navpreet_np
linkedin_username: navpreetsingh7
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  
  I am a masters student at NYU Courant primarily interested in Statistics, Machine Learning and Deep Learning.
  I have an experience of 2 years in Software Engineering including Backend Development (Oracle) and Machine Learning (NLP and ComputerVision).
  My research interests are in the field of Natural Language Understanding and Computer Vision.


content:

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Delhi Technological University
        caption: 2014 - 2018
        sub_title: Bachelor of Technology in Computer Science
        quote: >
          Delhi Technological University (DTU), formerly known as the Delhi College of Engineering (DCE) is a state university in New Delhi, India. It was established in 1941 as Delhi Polytechnic.
        description: | # this will include new lines to allow paragraphs
          During my time at DTU I gained alot of interest in Software Engineering. I learnt many key skills such as teamwork, punctuality and stick-to-itiveness that has been useful to me throughout my career. 

          

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Wissen Technology
        link: wissen.com
        # link_text: wissen.com
        sub_title: Software Engineer
        caption: November 2020 - January 2021
        quote: >
          Wissen is a leading technology consulting and solutions company practice primarily geared towards the domains of Banking & Finance, Telecom, and Healthcare.
        description: | # this will include new lines to allow paragraphs
            My work focused on training and implementing a Language Model for the Intelligent Search application for our client Baker Hughes. I implemented pdf parsing on the technical pdf documents as well as the BERT Transformer language model using sentence similarity for intelligent search.
      
      - layout: left
        title: MetricStream
        link: metricstream.com
        # link_text: metricstream.com
        sub_title: Member of Technical Staff - Developer
        caption: September 2018 - July 2020
        quote: >
          MetricStream is the world’s largest independent provider of governance, risk, and compliance (GRC) products & solutions.
        description: | # this will include new lines to allow paragraphs
            My primary focus was on the backend (Oracle SQL) part of the GRC Application for Risks and Audit modules with some work on custom configuration for the GRC application as well using the M7 platform.

      - layout: left
        title: inkers.ai
        link: inkers.ai
        # link_text: inkers.ai
        sub_title: Machine Learning Intern
        caption: March 2019 - September 2019
        quote: >
          We design and develop deep large-scale AI and ML vision solutions for Enterprises, Defence and Security Organizations. 
        description: | # this will include new lines to allow paragraphs
            This was a huge learning experience for me where I learnt to implement deep learning models for Computer Vision as well as Natural Language Processing.


  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Traffic vehicle tracking and speed estimation
        link: github.com/navpreetnp7/Car-Tracking-and-speed-estimation
        # link_text: Project Website
        additional_links:
          - title:  Car-Tracking-and-speed-estimation
            icon: fab fa-github
            url: github.com/navpreetnp7/Car-Tracking-and-speed-estimation
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Track vehicles on the road and estimate their speed.
        description: | # this will include new lines to allow paragraphs
          Implemented using Pretrained YOLOv4 on COCO dataset for object detection and DeepSort Model for object tracking. The application is able to detect vehicles in a video footage and estimate their speed in pixels/sec.
        quote: >  
          <img src="/images/demo.gif" height="250" width="250">
          
      - layout: top-middle
        title: Simple chatbot using seq2seq encoder-decoder model
        link: github.com/navpreetnp7/Chatbot
        # link_text: Project Website
        additional_links:
          - title:  Chatbot
            icon: fab fa-github
            url: github.com/navpreetnp7/Chatbot
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Simple chatbot trained on Movie Dialogues Dataset
        description: | # this will include new lines to allow paragraphs
          I trained a simple seq2seq model Chatbot using Pytorch based on multi-layered Gated Recurrent Unit (GRUs) and Attention mechanism using movie scripts dataset from the Cornell Movie-Dialogs Corpus.
          
          <img style="float: center;" src="/images/demo1.png" height="250" width="250">
          
      - layout: top-middle
        title: Automatic detection of malignant tumors in the lungs using CT scans
        link: github.com/navpreetnp7/LUNA-Challenge
        # link_text: Project Website
        additional_links:
          - title:  LUNA-Challenge
            icon: fab fa-github
            url: github.com/navpreetnp7/LUNA-Challenge
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Detection of tumors using Lung Nodule Analysis in CT Scans
        description: | # this will include new lines to allow paragraphs
          I trained an end-to-end complex deep neural network using Pytorch based on Lung Nodule Analysis dataset of chest CT scans, finding the nodules using simple CNN residual network architecture and then identifying the tumours using state of the art U-Net Architecture for Object Detection and Image segmentation and then using transfer learning to use the same resnet model to train and classify them as benign/malignant.
          
          <img style="float: center;" src="/images/demo2.png" height="250" width="250">
          
      - layout: top-middle
        title: DNA Classification
        link: github.com/navpreetnp7/DNA-Classification
        # link_text: Project Website
        additional_links:
          - title:  DNA-Classification
            icon: fab fa-github
            url: github.com/navpreetnp7/DNA-Classification
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Classification of DNA Sequence based on promoter region (where protein contact with DNA helix)
        description: | # this will include new lines to allow paragraphs
          I cleaned and prepared UCI DNA sequences data. Used exploratory data analysis to do feature engineering and trained the dataset on KNN, Decision Trees, SVM, Random Forest and Adaboost classifiers using pandas and sklearn to select the best performing model which was SVM.
          
      - layout: top-middle
        title: Predicting house prices
        link: github.com/navpreetnp7/Predicting-house-prices
        # link_text: Project Website
        additional_links:
          - title:  Predicting-house-prices
            icon: fab fa-github
            url: github.com/navpreetnp7/Predicting-house-prices
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Predicting house prices using Liner Regression trained on Ames Housing Dataset
        description: | # this will include new lines to allow paragraphs
          I cleaned, prepared, and visualised Ames Housing dataset and performed feature selection and feature engineering using pandas, seaborn and scipy. Then trained the data on Linear Regression techniques lasso and gradient boosting using sklearn and used ensemble method stacking and averaging the models to produce the best fit for the data.
          


  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in Software Engineering and Machine Learning, some of my other interests and hobbies are:
      - Book Reading. My recent favourites include Sapiens, Humankind: A hopeful history (Non Fiction)
      - Basketball
      - Travelling (Beaches, Mountain Trekking)

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
